// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"project-build/app/dao/internal"
)

// buildLogsDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type buildLogsDao struct {
	*internal.BuildLogsDao
}

var (
	// BuildLogs is globally public accessible object for table build_logs operations.
	BuildLogs buildLogsDao
)

func init() {
	BuildLogs = buildLogsDao{
		internal.NewBuildLogsDao(),
	}
}

// Fill with you ideas below.
