// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"project-build/app/dao/internal"
)

// projectDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type projectDao struct {
	*internal.ProjectDao
}

var (
	// Project is globally public accessible object for table project operations.
	Project projectDao
)

func init() {
	Project = projectDao{
		internal.NewProjectDao(),
	}
}

// Fill with you ideas below.
