// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"project-build/app/dao/internal"
)

// sqliteSequenceDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type sqliteSequenceDao struct {
	*internal.SqliteSequenceDao
}

var (
	// SqliteSequence is globally public accessible object for table sqlite_sequence operations.
	SqliteSequence sqliteSequenceDao
)

func init() {
	SqliteSequence = sqliteSequenceDao{
		internal.NewSqliteSequenceDao(),
	}
}

// Fill with you ideas below.
